# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 2.0.4"
gem 'sinatra-cross_origin', "~> 0.4.0"
gem "json", "~> 2.1.0"
gem "tanker-user-token", path: "../../"
